[package]
name = "egui-fb-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
egui_glow = "0.22.0"
framebuffer = "0.3.1"
glow = "0.12.3"
input = "0.8.3"
libc = "0.2.147"
