#!/bin/bash

run_hook() {
    echo "Mounting EFI vars filesystem..."
    mount -t efivarfs none /sys/firmware/efi/efivars
    echo "Launching boot menu..."
    openvt -f -c 37 -s -w  -- /bin/boot-menu
    modprobe nouveau
    echo "Boot menu exited, continuing boot..."
}
